/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author peperony
 */
public class Confi extends javax.swing.JPanel {

    /**
     * Creates new form Confi
     */
    public Confi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JTextField();
        Apellido1 = new javax.swing.JTextField();
        Apellido2 = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        Contrasenia = new javax.swing.JTextField();
        CambiarNombre = new javax.swing.JButton();
        CambiarApellido1 = new javax.swing.JButton();
        CambiarApellido2 = new javax.swing.JButton();
        CambiarCorreo = new javax.swing.JButton();
        CambiarContrasenia = new javax.swing.JButton();
        EliminarCuneta = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setBackground(new java.awt.Color(0, 204, 204));
        Nombre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        Nombre.setForeground(new java.awt.Color(51, 255, 0));
        add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 480, -1));

        Apellido1.setBackground(new java.awt.Color(0, 204, 204));
        Apellido1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        Apellido1.setForeground(new java.awt.Color(51, 255, 0));
        add(Apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 480, -1));

        Apellido2.setBackground(new java.awt.Color(0, 204, 204));
        Apellido2.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        Apellido2.setForeground(new java.awt.Color(51, 255, 0));
        add(Apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 470, -1));

        Correo.setBackground(new java.awt.Color(0, 204, 204));
        Correo.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        Correo.setForeground(new java.awt.Color(51, 255, 0));
        add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 470, -1));

        Contrasenia.setBackground(new java.awt.Color(0, 204, 204));
        Contrasenia.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        Contrasenia.setForeground(new java.awt.Color(51, 255, 0));
        add(Contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 470, -1));

        CambiarNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cambiar.png"))); // NOI18N
        CambiarNombre.setActionCommand("CambiarNombre");
        CambiarNombre.setBorderPainted(false);
        CambiarNombre.setContentAreaFilled(false);
        CambiarNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CambiarNombre.setFocusPainted(false);
        add(CambiarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 150, 50));

        CambiarApellido1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cambiar.png"))); // NOI18N
        CambiarApellido1.setActionCommand("CambiarApellido1");
        CambiarApellido1.setBorderPainted(false);
        CambiarApellido1.setContentAreaFilled(false);
        CambiarApellido1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CambiarApellido1.setFocusPainted(false);
        add(CambiarApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 160, 50));

        CambiarApellido2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cambiar.png"))); // NOI18N
        CambiarApellido2.setActionCommand("CambiarApellido2");
        CambiarApellido2.setBorderPainted(false);
        CambiarApellido2.setContentAreaFilled(false);
        CambiarApellido2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CambiarApellido2.setFocusPainted(false);
        add(CambiarApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 150, 50));

        CambiarCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cambiar.png"))); // NOI18N
        CambiarCorreo.setActionCommand("CambiarCorreo");
        CambiarCorreo.setBorderPainted(false);
        CambiarCorreo.setContentAreaFilled(false);
        CambiarCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CambiarCorreo.setFocusPainted(false);
        add(CambiarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 150, -1));

        CambiarContrasenia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cambiar.png"))); // NOI18N
        CambiarContrasenia.setBorderPainted(false);
        CambiarContrasenia.setContentAreaFilled(false);
        CambiarContrasenia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CambiarContrasenia.setFocusPainted(false);
        add(CambiarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, 150, -1));

        EliminarCuneta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Eliminar.png"))); // NOI18N
        EliminarCuneta.setActionCommand("ELiminarCuenta");
        EliminarCuneta.setBorderPainted(false);
        EliminarCuneta.setContentAreaFilled(false);
        EliminarCuneta.setFocusPainted(false);
        add(EliminarCuneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 320, 230, 230));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Salir.png"))); // NOI18N
        salir.setActionCommand("Salir");
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setFocusPainted(false);
        add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 140, 50));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Atras.png"))); // NOI18N
        atras.setActionCommand("AtrasConfi");
        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.setFocusPainted(false);
        add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 670, 70, 70));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Cambiar Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 60));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Cambiar Primer Apellido:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Cambiar Segundo Apellido:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Cambiar Correo Electronico:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Cambiar Contraseña:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fondo2.jpg"))); // NOI18N
        jLabel1.setText("}");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Apellido1;
    public javax.swing.JTextField Apellido2;
    public javax.swing.JButton CambiarApellido1;
    public javax.swing.JButton CambiarApellido2;
    public javax.swing.JButton CambiarContrasenia;
    public javax.swing.JButton CambiarCorreo;
    public javax.swing.JButton CambiarNombre;
    public javax.swing.JTextField Contrasenia;
    public javax.swing.JTextField Correo;
    public javax.swing.JButton EliminarCuneta;
    public javax.swing.JTextField Nombre;
    public javax.swing.JButton atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
