/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author peperony
 */
public class Contrasenia extends javax.swing.JPanel {

    /**
     * Creates new form Contrasenia
     */
    public Contrasenia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IniciarSesion = new javax.swing.JButton();
        Registrarse = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/IniciarSesion.png"))); // NOI18N
        IniciarSesion.setActionCommand("IniciarSesion");
        IniciarSesion.setBorderPainted(false);
        IniciarSesion.setContentAreaFilled(false);
        IniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 440, 70));

        Registrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Registrarse.png"))); // NOI18N
        Registrarse.setActionCommand("Registrarse");
        Registrarse.setBorderPainted(false);
        Registrarse.setContentAreaFilled(false);
        Registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(Registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 440, 70));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Salir.png"))); // NOI18N
        Salir.setActionCommand("Salir");
        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 140, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fondo1.jpg"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton IniciarSesion;
    public javax.swing.JButton Registrarse;
    public javax.swing.JButton Salir;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
