/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author peperony
 */
public class CrearPartida extends javax.swing.JPanel {

    /**
     * Creates new form CrearPartida
     */
    public CrearPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldColumnas = new javax.swing.JTextField();
        jTextFieldFilas = new javax.swing.JTextField();
        Rojo = new javax.swing.JRadioButton();
        azul = new javax.swing.JRadioButton();
        Verde = new javax.swing.JRadioButton();
        jButtonComenzar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Salir.png"))); // NOI18N
        salir.setActionCommand("Salir");
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setFocusPainted(false);
        add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 140, 50));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Atras.png"))); // NOI18N
        atras.setActionCommand("AtrasCrearPartida");
        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.setFocusPainted(false);
        add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 670, 70, 70));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Nombre de la partida:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jTextFieldNombre.setBackground(new java.awt.Color(0, 204, 204));
        jTextFieldNombre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(255, 255, 0));
        add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 590, -1));

        jTextFieldColumnas.setBackground(new java.awt.Color(0, 204, 204));
        jTextFieldColumnas.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jTextFieldColumnas.setForeground(new java.awt.Color(255, 255, 0));
        add(jTextFieldColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 80, -1));

        jTextFieldFilas.setBackground(new java.awt.Color(0, 204, 204));
        jTextFieldFilas.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jTextFieldFilas.setForeground(new java.awt.Color(255, 255, 0));
        add(jTextFieldFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 80, -1));

        Rojo.setBackground(new java.awt.Color(51, 51, 255));
        Rojo.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Rojo.setForeground(new java.awt.Color(255, 51, 51));
        Rojo.setText("Rojo");
        Rojo.setFocusPainted(false);
        add(Rojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, -1, -1));

        azul.setBackground(new java.awt.Color(51, 51, 255));
        azul.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        azul.setForeground(new java.awt.Color(255, 51, 51));
        azul.setText("Azul");
        azul.setActionCommand("azul");
        azul.setFocusPainted(false);
        add(azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 450, -1, -1));

        Verde.setBackground(new java.awt.Color(51, 51, 250));
        Verde.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Verde.setForeground(new java.awt.Color(255, 51, 51));
        Verde.setText("Verde");
        Verde.setActionCommand("verde");
        Verde.setFocusPainted(false);
        add(Verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 450, -1, -1));

        jButtonComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AceptarRegistrar.png"))); // NOI18N
        jButtonComenzar.setActionCommand("ComenzarPartida");
        jButtonComenzar.setBorderPainted(false);
        jButtonComenzar.setContentAreaFilled(false);
        jButtonComenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonComenzar.setFocusPainted(false);
        add(jButtonComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 350, 90));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Color de la ficha:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("Columnas:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Filas:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fondo2.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton Rojo;
    public javax.swing.JRadioButton Verde;
    public javax.swing.JButton atras;
    public javax.swing.JRadioButton azul;
    public javax.swing.JButton jButtonComenzar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField jTextFieldColumnas;
    public javax.swing.JTextField jTextFieldFilas;
    public javax.swing.JTextField jTextFieldNombre;
    public javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
