/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author peperony
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldContrasenia = new javax.swing.JTextField();
        Salir = new javax.swing.JButton();
        jButtonAceptarLogin = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldUsuario.setBackground(new java.awt.Color(0, 255, 204));
        jTextFieldUsuario.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 430, -1));

        jTextFieldContrasenia.setBackground(new java.awt.Color(51, 255, 204));
        jTextFieldContrasenia.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        add(jTextFieldContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 430, -1));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Salir.png"))); // NOI18N
        Salir.setActionCommand("Salir");
        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.setFocusPainted(false);
        add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 140, 50));

        jButtonAceptarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AceptarRegistrar.png"))); // NOI18N
        jButtonAceptarLogin.setActionCommand("AceptarLogin");
        jButtonAceptarLogin.setBorderPainted(false);
        jButtonAceptarLogin.setContentAreaFilled(false);
        jButtonAceptarLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAceptarLogin.setFocusPainted(false);
        add(jButtonAceptarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, -1, -1));

        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Atras.png"))); // NOI18N
        Atras.setActionCommand("AtrasLoguin");
        Atras.setBorderPainted(false);
        Atras.setContentAreaFilled(false);
        Atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Atras.setDefaultCapable(false);
        Atras.setFocusPainted(false);
        add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 670, 70, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("Usuario:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Contraseña:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fondo1.jpg"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Atras;
    public javax.swing.JButton Salir;
    public javax.swing.JButton jButtonAceptarLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    public javax.swing.JTextField jTextFieldContrasenia;
    public javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
