/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author peperony
 */
public class MenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        jButtonCrearPartida = new javax.swing.JButton();
        jButtonUnircePartida = new javax.swing.JButton();
        jButtonEspectar = new javax.swing.JButton();
        jButtonRanking = new javax.swing.JButton();
        jButtonConfing = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Salir.png"))); // NOI18N
        Salir.setActionCommand("Salir");
        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.setFocusPainted(false);
        add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 140, 50));

        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Atras.png"))); // NOI18N
        Atras.setActionCommand("AtrasMPrincipal");
        Atras.setBorderPainted(false);
        Atras.setContentAreaFilled(false);
        Atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Atras.setFocusPainted(false);
        add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 670, 70, 70));

        jButtonCrearPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CrearPartida.png"))); // NOI18N
        jButtonCrearPartida.setActionCommand("CrearPartida");
        jButtonCrearPartida.setBorderPainted(false);
        jButtonCrearPartida.setContentAreaFilled(false);
        jButtonCrearPartida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCrearPartida.setFocusPainted(false);
        add(jButtonCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 470, 80));

        jButtonUnircePartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/UnircePartida.png"))); // NOI18N
        jButtonUnircePartida.setActionCommand("UnircePartida");
        jButtonUnircePartida.setBorderPainted(false);
        jButtonUnircePartida.setContentAreaFilled(false);
        jButtonUnircePartida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUnircePartida.setFocusPainted(false);
        add(jButtonUnircePartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 470, -1));

        jButtonEspectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Expetador.png"))); // NOI18N
        jButtonEspectar.setActionCommand("Espectador");
        jButtonEspectar.setBorderPainted(false);
        jButtonEspectar.setContentAreaFilled(false);
        jButtonEspectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEspectar.setFocusPainted(false);
        add(jButtonEspectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 470, -1));

        jButtonRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ranking.png"))); // NOI18N
        jButtonRanking.setActionCommand("ranking");
        jButtonRanking.setBorderPainted(false);
        jButtonRanking.setContentAreaFilled(false);
        jButtonRanking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRanking.setFocusPainted(false);
        add(jButtonRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 480, -1));

        jButtonConfing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/config.png"))); // NOI18N
        jButtonConfing.setActionCommand("Confi");
        jButtonConfing.setBorderPainted(false);
        jButtonConfing.setContentAreaFilled(false);
        jButtonConfing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConfing.setFocusPainted(false);
        add(jButtonConfing, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fondo2.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Atras;
    public javax.swing.JButton Salir;
    public javax.swing.JButton jButtonConfing;
    public javax.swing.JButton jButtonCrearPartida;
    public javax.swing.JButton jButtonEspectar;
    public javax.swing.JButton jButtonRanking;
    public javax.swing.JButton jButtonUnircePartida;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
