/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author peperony
 */
public class Registrar extends javax.swing.JPanel {

    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        jButtonAceptarRegistrar = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido1 = new javax.swing.JLabel();
        jLabelApellido2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Salir.png"))); // NOI18N
        Salir.setActionCommand("Salir");
        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.setDefaultCapable(false);
        add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 140, 50));

        jButtonAceptarRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/AceptarRegistrar.png"))); // NOI18N
        jButtonAceptarRegistrar.setActionCommand("AceptarRegistrar");
        jButtonAceptarRegistrar.setBorderPainted(false);
        jButtonAceptarRegistrar.setContentAreaFilled(false);
        jButtonAceptarRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButtonAceptarRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, 350, 90));

        Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Atras.png"))); // NOI18N
        Atras.setToolTipText("");
        Atras.setActionCommand("AtrasRegistrar");
        Atras.setBorderPainted(false);
        Atras.setContentAreaFilled(false);
        Atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 670, 70, 70));

        jTextFieldNombre.setBackground(new java.awt.Color(51, 204, 255));
        jTextFieldNombre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(204, 0, 204));
        add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 440, 50));

        jTextFieldApellido1.setBackground(new java.awt.Color(0, 204, 255));
        jTextFieldApellido1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jTextFieldApellido1.setForeground(new java.awt.Color(204, 0, 204));
        jTextFieldApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellido1ActionPerformed(evt);
            }
        });
        add(jTextFieldApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 440, -1));

        jTextFieldApellido2.setBackground(new java.awt.Color(0, 204, 255));
        jTextFieldApellido2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jTextFieldApellido2.setForeground(new java.awt.Color(204, 0, 204));
        add(jTextFieldApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 440, -1));

        jTextFieldCorreo.setBackground(new java.awt.Color(0, 204, 255));
        jTextFieldCorreo.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jTextFieldCorreo.setForeground(new java.awt.Color(204, 0, 204));
        add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 440, -1));

        jLabelNombre.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(204, 0, 204));
        jLabelNombre.setText("Nombre:");
        add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, 50));

        jLabelApellido1.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabelApellido1.setForeground(new java.awt.Color(204, 0, 204));
        jLabelApellido1.setText("Primer apellido:");
        add(jLabelApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabelApellido2.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabelApellido2.setForeground(new java.awt.Color(204, 0, 204));
        jLabelApellido2.setText("Segundo apellido:");
        add(jLabelApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Correo:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fondo1.jpg"))); // NOI18N
        add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellido1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Atras;
    public javax.swing.JButton Salir;
    public javax.swing.JButton jButtonAceptarRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNombre;
    public javax.swing.JTextField jTextFieldApellido1;
    public javax.swing.JTextField jTextFieldApellido2;
    public javax.swing.JTextField jTextFieldCorreo;
    public javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
