/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inicio;

/**
 *
 * @author peperony
 */
public class Comeinzo extends javax.swing.JPanel {

    /**
     * Creates new form Comeinzo
     */
    public Comeinzo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCliente = new javax.swing.JButton();
        jButtonServidor = new javax.swing.JButton();
        jLabelIp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cliente.png"))); // NOI18N
        jButtonCliente.setActionCommand("Server");
        jButtonCliente.setBorderPainted(false);
        jButtonCliente.setContentAreaFilled(false);
        jButtonCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCliente.setFocusPainted(false);
        add(jButtonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        jButtonServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Servidor.png"))); // NOI18N
        jButtonServidor.setActionCommand("Servidor");
        jButtonServidor.setBorderPainted(false);
        jButtonServidor.setContentAreaFilled(false);
        jButtonServidor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonServidor.setFocusPainted(false);
        add(jButtonServidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, -1, -1));

        jLabelIp.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabelIp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabelIp, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 590, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Fondo1.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCliente;
    public javax.swing.JButton jButtonServidor;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelIp;
    // End of variables declaration//GEN-END:variables
}
